import * as UUID from 'uuid'

export const Events = {
  LIGHT_BOX_IMAGE_RAY_UPDATE: UUID.v1(),
  IMAGE_SCREEN_LOAD_UPDATE: UUID.v1(),
  ORIGIN_UPDATE: UUID.v1(),
  TILE_SERVICE_STATUS_UPDATE: UUID.v1(),
  KEYUP: UUID.v1(),
  KEYDOWN: UUID.v1(),
  LIGHTBOX_CLOSE: UUID.v1(),
  IMAGE_EDIT_STATE: UUID.v1(),
  IMAGE_CLICK: UUID.v1(),
  SCENE_UPDATED: UUID.v1(),
}
